export const products = [
  {
    id: 0,
    name: "Localizador GPS PitPat para Perros sin Suscripción",
    marca: "PitPat",
    category: "Mixto",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/810RZQFbhHL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4vHpEfN",
    isFeatured: true,
    valoracion_media: 4.4,
    pros: "Sin suscripción mensual ni cuotas fijas|Batería de larguísima duración de hasta 1 año|Monitor de actividad física y descanso muy preciso|Estructura sumergible IP68 y robusta",
    contras: "Precio de compra inicial superior|No cuenta con voz o micrófono integrado",
    radar_scores: [8, 10, 7, 9, 8, 9],
    description: "El localizador GPS PitPat para perros te permite encontrar a tu mascota sin preocuparte por pagos mensuales. Además de una localización precisa, funciona como un podómetro inteligente para controlar el ejercicio de tu perro."
  },
  {
    id: 1,
    name: "Collar GPS Tractive para Perros con Seguimiento en Tiempo Real",
    marca: "Tractive",
    category: "Urbano",
    tipo_uso: "urbano",
    image_url: "https://m.media-amazon.com/images/I/71il4nMReSL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/3RclVrl",
    isFeatured: true,
    valoracion_media: 4.6,
    pros: "Localización precisa en tiempo real ilimitada|Alertas instantáneas de escape con valla virtual|Monitorización avanzada del sueño y bienestar diario|Enganche de silicona cómodo y seguro",
    contras: "Requiere plan de suscripción mensual|Autonomía máxima de 7 días",
    radar_scores: [9, 6, 9, 9, 9, 8],
    description: "Tractive es el estándar de oro en collares GPS para perros. Te ofrece un rastreo inmediato en tu móvil con cobertura en decenas de países, avisándote al instante si tu perro sale del jardín."
  },
  {
    id: 2,
    name: "Weenect Dog XS Localizador GPS Mini para Perros",
    marca: "Weenect",
    category: "Mixto",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/61SEyT69V7L._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/3SSncUY",
    isFeatured: false,
    valoracion_media: 4.3,
    pros: "El rastreador GPS más pequeño y ligero del mercado|Seguimiento en tiempo real interactivo sin límite|Tarjeta SIM multi-red integrada para cobertura óptima|Herramienta de adiestramiento por vibración",
    contras: "Requiere plan de suscripción obligatorio|Duración de batería de 3 días promedio",
    radar_scores: [9, 5, 8, 10, 8, 7],
    description: "El Weenect Dog XS destaca por su diseño ultraligero que no molesta a la mascota. Ofrece un rastreo milimétrico paso a paso, ideal para perros pequeños y medianos que disfrutan correr libres."
  },
  {
    id: 3,
    name: "Weenect Dog Localizador GPS Impermeable con Alerta Antifuga",
    marca: "Weenect",
    category: "Mixto",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/71FPyG+WWUL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4wjPoP4",
    isFeatured: false,
    valoracion_media: 4.2,
    pros: "Localización en vivo sin límites de distancia|Alerta inmediata si sale de las zonas seguras|Linterna LED integrada para búsquedas en la oscuridad|Historial detallado de todas sus rutas",
    contras: "Exige plan de suscripción mensual|Curva de configuración inicial técnica",
    radar_scores: [8, 6, 8, 8, 8, 8],
    description: "Este rastreador Weenect robusto ofrece una localización continua y confiable en cualquier situación. Cuenta con funciones acústicas y de vibración para entrenar el retorno a casa de tu perro."
  },
  {
    id: 4,
    name: "Tractive GPS Adventure Localizador Reforzado para Perros",
    marca: "Tractive",
    category: "Caza",
    tipo_uso: "caza",
    image_url: "https://m.media-amazon.com/images/I/81hjcH1tQGL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4gg0qjI",
    isFeatured: true,
    valoracion_media: 4.7,
    pros: "Carcasa ultra resistente ideal para senderismo y campo|Totalmente sumergible en agua dulce o salada|Alertas de valla virtual instantáneas en el móvil|Rastreo de actividad física y quema de calorías",
    contras: "Requiere cuota de suscripción periódica|Es ligeramente más pesado que el modelo estándar",
    radar_scores: [9, 7, 9, 7, 9, 8],
    description: "Diseñado para los perros más intrépidos, el Tractive Adventure cuenta con una protección reforzada contra golpes y mordidas. Ideal para caminatas en la naturaleza, caza o terrenos complicados."
  },
  {
    id: 5,
    name: "PAJ GPS Localizador para Perros 4G de Cobertura Global",
    marca: "PAJ GPS",
    category: "Mixto",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/810j0GUWuZL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4gbMjvL",
    isFeatured: false,
    valoracion_media: 4.4,
    pros: "Tecnología 4G de alta velocidad con excelente cobertura|Alertas de velocidad y salida de valla de seguridad|Materiales alemanes de gran durabilidad y tacto suave|Funda de silicona resistente a las salpicaduras",
    contras: "Requiere suscripción activa para usar la SIM|Dimensiones óptimas para perros de más de 4.5kg",
    radar_scores: [9, 8, 9, 8, 8, 8],
    description: "Con una antena GPS de gran sensibilidad y conectividad 4G LTE, este localizador PAJ te asegura encontrar a tu perro rápido en campo abierto o zonas urbanas en toda Europa."
  },
  {
    id: 6,
    name: "Localizador GPS Inteligente sin Cuotas compatible iOS",
    marca: "Compatible iOS",
    category: "Urbano",
    tipo_uso: "urbano",
    image_url: "https://m.media-amazon.com/images/I/81CJmBZhnQL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4bhtVhu",
    isFeatured: false,
    valoracion_media: 4.1,
    pros: "Completamente libre de suscripciones y cuotas mensuales|Batería reemplazable estándar de un año de duración|Integración perfecta con la aplicación Buscar de Apple|Ultra ligero y cómodo para gatos y perros pequeños",
    contras: "No es GPS satelital en tiempo real directo|Depende de la cercanía de dispositivos Apple",
    radar_scores: [6, 10, 5, 9, 7, 9],
    description: "La solución más económica y ligera para mascotas tranquilas en entornos urbanos. Se integra con la red global Buscar de Apple para localizar a tu mascota sin pagar cuotas."
  },
  {
    id: 7,
    name: "Valla Inalámbrica Inteligente y GPS de Entrenamiento",
    marca: "Inalámbrico",
    category: "Caza",
    tipo_uso: "caza",
    image_url: "https://m.media-amazon.com/images/I/71KdcdE2cSL._AC_SL1500_.jpg",
    affiliate_link: "https://www.amazon.es/dp/B0F48FZLSS?tag=sosa0af-21",
    isFeatured: false,
    valoracion_media: 4.0,
    pros: "Valla de seguridad circular GPS totalmente portátil|Sin cuotas de suscripción de ningún tipo|Rango de control amplio ideal para parcelas grandes|Collar impermeable y resistente para exteriores",
    contras: "Diseñado para exteriores despejados, no interiores|No rastrea rutas paso a paso",
    radar_scores: [7, 8, 9, 6, 6, 8],
    description: "Este dispositivo actúa como un sistema de contención virtual automático para terrenos amplios. Define límites seguros mediante coordenadas GPS para mantener a tu mascota protegida."
  },
  {
    id: 8,
    name: "Rastreador GPS para Mascotas Impermeable con Salud",
    marca: "Rastreador",
    category: "Urbano",
    tipo_uso: "urbano",
    image_url: "https://m.media-amazon.com/images/I/81lKNe9TWaL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4f8IZ3r",
    isFeatured: false,
    valoracion_media: 4.2,
    pros: "Excelente precisión de posicionamiento satelital|Resistencia al agua certificada IP68 contra chapuzones|Seguimiento del ejercicio diario y calorías de la mascota|Notificaciones rápidas en pantalla de tu smartphone",
    contras: "Requiere suscripción activa para la red de datos|Autonomía típica de unos 5 días",
    radar_scores: [8, 7, 8, 8, 7, 8],
    description: "Un localizador GPS integral que protege la vida de tu mascota y analiza su salud. Monitoriza de forma continua su ubicación en tiempo real y detecta anomalías en su descanso."
  },
  {
    id: 9,
    name: "Localizador GPS con Micrófono y Llamada sin Suscripción",
    marca: "Suscripción Libre",
    category: "Mixto",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/61JDzYQzN6L._AC_SL1000_.jpg",
    affiliate_link: "https://amzn.to/4aqJD9R",
    isFeatured: false,
    valoracion_media: 3.9,
    pros: "Totalmente libre de cuotas mensuales fijas de la marca|Micrófono integrado para escuchar el entorno de la mascota|Soporta llamadas de voz de retorno rápidas|Localización exacta mediante satélites GPS en vivo",
    contras: "Debes comprar tu propia tarjeta SIM de prepago|La aplicación móvil utiliza una interfaz genérica",
    radar_scores: [8, 8, 7, 7, 6, 9],
    description: "Este innovador rastreador sin suscripción te permite escuchar lo que ocurre alrededor de tu perro. Es perfecto para dueños que quieren un control de seguridad total sin ataduras financieras."
  },
  {
    id: 10,
    name: "Localizador GPS Compacto Universal sin Cuotas de Servicio",
    marca: "Inteligente",
    category: "Urbano",
    tipo_uso: "urbano",
    image_url: "https://m.media-amazon.com/images/I/61AJJ+gBTAL._AC_.jpg",
    affiliate_link: "https://amzn.to/4gaXLYv",
    isFeatured: false,
    valoracion_media: 3.8,
    pros: "Sin suscripción de por vida para el servicio de mapas|Diseño sumamente compacto adaptable a cualquier mascota|Funda de silicona de protección anticaídas incluida|Ubicación precisa en tiempo real en zonas cubiertas",
    contras: "La configuración inicial se realiza mediante comandos SMS|Manual de instrucciones poco detallado",
    radar_scores: [7, 7, 6, 9, 6, 8],
    description: "Un dispositivo práctico y duradero para evitar pérdidas accidentales de perros y gatos. Su tamaño mini lo convierte en una excelente opción para collares tradicionales ligeros."
  },
  {
    id: 11,
    name: "Localizador GPS de Gatos y Mascotas sin Suscripción",
    marca: "Cat Tracker",
    category: "Mini",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/81vYd6WcyDL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4eQFcX3",
    isFeatured: false,
    valoracion_media: 3.7,
    pros: "Sin suscripciones fijas ni cuotas mensuales adicionales|Muy liviano e ideal para gatos y perros miniatura|Estuche de silicona flexible de ajuste perfecto|Localización precisa en campo abierto",
    contras: "Capacidad de batería reducida debido a su ligereza|Menor cobertura en interiores de edificios",
    radar_scores: [7, 6, 6, 10, 6, 8],
    description: "El rastreador mini definitivo para felinos aventureros y perros miniatura. Monitorea sus escapadas diarias con total tranquilidad y sin tener que pagar recibos mensuales de servicio."
  },
  {
    id: 12,
    name: "TKMARS Localizador GPS de Alta Autonomía y Resistencia",
    marca: "TKMARS",
    category: "Caza",
    tipo_uso: "caza",
    image_url: "https://m.media-amazon.com/images/I/61B-hjmY9dL._AC_SL1000_.jpg",
    affiliate_link: "https://amzn.to/3Qv7v5x",
    isFeatured: false,
    valoracion_media: 4.5,
    pros: "Batería descomunal de larga autonomía (hasta 30 días)|Precisión satelital insuperable en zonas boscosas|Estructura estanca de alta resistencia ante golpes|Historial completo de rutas de los últimos 180 días",
    contras: "Ligeramente voluminoso para mascotas de menos de 5 kg|No recomendado para felinos pequeños",
    radar_scores: [9, 10, 9, 6, 7, 8],
    description: "Si buscas un rastreador que dure semanas sin cargarse, este modelo TKMARS es la elección ideal. Perfecto para perros grandes de campo, senderismo avanzado o zonas de montaña."
  },
  {
    id: 13,
    name: "Pawfit 2 Localizador GPS Inteligente de Mascotas",
    marca: "Pawfit",
    category: "Mixto",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/6178B4jDKkL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/3Rerbuy",
    isFeatured: false,
    valoracion_media: 4.4,
    pros: "Monitoreo completo de salud y nivel de actividad|Comandos de voz personalizados que puedes reproducir de lejos|Protección impermeable premium IP68 a prueba de buceo|Alarma de temperatura extrema para tu tranquilidad",
    contras: "Plan de suscripción mensual obligatorio|Fijación al collar un poco rígida",
    radar_scores: [8, 7, 8, 8, 9, 8],
    description: "Pawfit 2 destaca por combinar rastreo de alta seguridad con un entrenador por voz y monitor de bienestar. Es ideal para mantener en forma a tu perro mientras está perfectamente ubicado."
  },
  {
    id: 14,
    name: "PETLOC8 Localizador GPS con Luces de Seguridad",
    marca: "PETLOC8",
    category: "Urbano",
    tipo_uso: "urbano",
    image_url: "https://m.media-amazon.com/images/I/81OB0BI6LkL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/3Qv7wX9",
    isFeatured: false,
    valoracion_media: 4.1,
    pros: "Luz de seguridad LED integrada para paseos nocturnos|Excelente aplicación con interfaz intuitiva en español|Muy cómodo y fácil de abrochar en cualquier arnés|Notificaciones rápidas al salir del perímetro virtual",
    contras: "Suscripción obligatoria para activar la tarjeta SIM|La cobertura se puede ver mermada en valles profundos",
    radar_scores: [8, 6, 8, 9, 8, 7],
    description: "Este elegante collar GPS cuenta con iluminación de seguridad ideal para pasear a tu perro por la noche. Ofrece un control exacto del movimiento de tu mascota con total comodidad."
  },
  {
    id: 15,
    name: "Localizador GPS sin Suscripción Universal Perros y Gatos",
    marca: "Suscripción Libre",
    category: "Mixto",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/71LHcK-1mgL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4vb2TzN",
    isFeatured: false,
    valoracion_media: 4.0,
    pros: "Totalmente libre de tarifas y cuotas mensuales fijas|Diseño versátil apto tanto para perros como para gatos|Configuración rápida de valla virtual mediante app|Batería duradera con modo de ahorro inteligente",
    contras: "Se requiere adquirir una tarjeta SIM móvil prepago|No registra mapas de calor de comportamiento",
    radar_scores: [8, 8, 7, 9, 6, 9],
    description: "Una opción altamente rentable para quienes quieren evitar los costes de suscripción. Permite geolocalizar a tu mascota en tiempo real de forma fácil y directa desde tu smartphone."
  },
  {
    id: 16,
    name: "Winnes Localizador GPS con Estadísticas de Bienestar",
    marca: "Winnes",
    category: "Urbano",
    tipo_uso: "urbano",
    image_url: "https://m.media-amazon.com/images/I/61o9+MxmjGL._AC_SL1200_.jpg",
    affiliate_link: "https://amzn.to/4wd3lOG",
    isFeatured: false,
    valoracion_media: 4.1,
    pros: "Análisis pormenorizado de actividad y descanso|Diseño premium con funda elástica de silicona suave|Rastreo continuo en vivo muy fluido en el mapa|Excelente empaquetado e instrucciones claras",
    contras: "Suscripción móvil obligatoria para la tarjeta celular|Tiempo de recarga de batería de unas 3 horas",
    radar_scores: [8, 6, 8, 8, 8, 8],
    description: "Winnes es una opción equilibrada para monitorear el comportamiento de tu perro. Su aplicación te detalla la intensidad del ejercicio diario, ayudándote a cuidar su salud física."
  },
  {
    id: 17,
    name: "Tractive CAT Mini Localizador GPS para Gatos con Collar",
    marca: "Tractive",
    category: "Mini",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/71hJIvr80oL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4bdLvD1",
    isFeatured: true,
    valoracion_media: 4.5,
    pros: "Diseño ergonómico exclusivo para la anatomía del gato|Collar de seguridad Rogz con cierre anti-enganches|Mapa de calor de territorio para ver dónde pasa el tiempo|Rastreo en vivo sin límites de distancia",
    contras: "Requiere plan de suscripción mensual|Autonomía máxima de 2 a 3 días",
    radar_scores: [9, 5, 8, 10, 9, 8],
    description: "El rastreador definitivo para gatos audaces. Cuenta con un sistema de liberación de seguridad que evita asfixias y te desvela los misterios de las rutas nocturnas de tu felino."
  },
  {
    id: 18,
    name: "Kippy Cat V2 Localizador de Gatos Antiestrangulamiento",
    marca: "Kippy",
    category: "Mini",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/71I5w9Fks1L._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4vHUF37",
    isFeatured: false,
    valoracion_media: 4.2,
    pros: "Collar especial de seguridad antiestrangulamiento incluido|Seguimiento detallado de la actividad física y sueño|Ubicación precisa en tiempo real con actualizaciones rápidas|Alertas instantáneas de salida de zonas seguras",
    contras: "Suscripción activa obligatoria|Batería de unos 2 días en seguimiento continuo",
    radar_scores: [8, 5, 8, 9, 8, 7],
    description: "Un localizador premium para felinos con un collar elástico de seguridad. Monitoriza tanto su salud como su ubicación para garantizar que tu gato esté siempre sano y salvo."
  },
  {
    id: 19,
    name: "Denash Localizador GPS de Acople para Collar de Mascotas",
    marca: "Denash",
    category: "Mixto",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/61dkHLJTpVL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4vHNojO",
    isFeatured: false,
    valoracion_media: 3.9,
    pros: "Ligero y compacto de fácil sujeción a collares estándar|Sin suscripciones fijas ni cuotas mensuales recurrentes|Localización SMS rápida y consumo de datos bajísimo|Buena resistencia al polvo y salpicaduras",
    contras: "Requiere que proporciones tu propia tarjeta SIM activa|No cuenta con sensores de salud",
    radar_scores: [7, 8, 6, 9, 6, 8],
    description: "Un localizador práctico e independiente para fijar a la correa de tu perro o gato. Ofrece un posicionamiento confiable mediante comandos sencillos sin atarte a contratos mensuales."
  }
];
