export const products = [
  {
    id: 0,
    name: "Localizador GPS PitPat para Perros sin Suscripción",
    marca: "PitPat",
    category: "Mixto",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/810RZQFbhHL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4vHpEfN",
    isFeatured: true,
    valoracion_media: 4.4,
    pros: "Sin suscripción mensual ni cuotas fijas|Batería de larguísima duración de hasta 1 año|Monitor de actividad física y descanso muy preciso|Estructura sumergible IP68 y robusta",
    contras: "Precio de compra inicial superior|No cuenta con voz o micrófono integrado",
    radar_scores: [8, 10, 7, 9, 8, 9],
    description: "El localizador GPS PitPat para perros es una de las soluciones más fiables si buscas un collar GPS sin suscripción mensual ni cuotas de mantenimiento adicionales en el mercado actual. Al comprar el dispositivo, tienes acceso ilimitado de por vida a la localización por satélite, utilizando tecnología de posicionamiento de alta precisión para geolocalizar a tu mascota en cualquier momento. Además de localizar a tu perro en tiempo real si se escapa, este ligero collar actúa como un podómetro inteligente de gran precisión, registrando el ejercicio físico diario, las calorías quemadas, las distancias recorridas y las horas de sueño profundo o descanso. Su carcasa IP68 es sumamente robusta y totalmente impermeable, ideal para paseos por el campo, el fango o incluso si a tu perro le gusta nadar en ríos o playas. Su batería reemplazable estándar dura hasta un año entero, eliminando por completo la pesadez de tener que recargar el dispositivo cada pocos días y ofreciéndote una total tranquilidad."
  },
  {
    id: 1,
    name: "Collar GPS Tractive para Perros con Seguimiento en Tiempo Real",
    marca: "Tractive",
    category: "Urbano",
    tipo_uso: "urbano",
    image_url: "https://m.media-amazon.com/images/I/71il4nMReSL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/3RclVrl",
    isFeatured: true,
    valoracion_media: 4.6,
    pros: "Localización precisa en tiempo real ilimitada|Alertas instantáneas de escape con valla virtual|Monitorización avanzada del sueño y bienestar diario|Enganche de silicona cómodo y seguro",
    contras: "Requiere plan de suscripción mensual|Autonomía máxima de 7 días",
    radar_scores: [9, 6, 9, 9, 9, 8],
    description: "El collar GPS Tractive para perros es el líder indiscutible en sistemas de seguimiento en tiempo real y localización inmediata en toda España y Europa. Este completo localizador utiliza una tarjeta SIM multi-red integrada que se conecta a las mejores redes móviles de telefonía disponibles en cada momento, garantizándote cobertura global sin límites de distancia. En tu teléfono móvil, a través de la aplicación oficial de Tractive, recibirás notificaciones instantáneas si tu mascota sale del jardín gracias al avanzado sistema de valla virtual de seguridad. Además, dispone de una función 'Live' para actualizaciones de ubicación cada 2-3 segundos y un modo de monitorización de salud que evalúa la calidad del sueño de tu perro, sus periodos de calma y la quema de calorías diarias. Su batería recargable ofrece una autonomía de entre 5 y 7 días según el uso, y su enganche de silicona flexible se ajusta de forma cómoda y firme a cualquier tipo de collar estándar."
  },
  {
    id: 2,
    name: "Weenect Dog XS Localizador GPS Mini para Perros",
    marca: "Weenect",
    category: "Mixto",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/61SEyT69V7L._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/3SSncUY",
    isFeatured: false,
    valoracion_media: 4.3,
    pros: "El rastreador GPS más pequeño y ligero del mercado|Seguimiento en tiempo real interactivo sin límite|Tarjeta SIM multi-red integrada para cobertura óptima|Herramienta de adiestramiento por vibración",
    contras: "Requiere plan de suscripción obligatorio|Duración de batería de 3 días promedio",
    radar_scores: [9, 5, 8, 10, 8, 7],
    description: "El Weenect Dog XS destaca por su diseño ultraligero que no molesta a la mascota en sus movimientos cotidianos. Con solo 27 gramos de peso, este minúsculo dispositivo de fabricación europea ofrece una localización en tiempo real continua y sin límites de distancia, actualizando su posición cada pocos segundos de forma fluida. Su tarjeta SIM multi-red integrada ofrece cobertura en prácticamente toda Europa, conectándose a redes de telefonía celular 5G/4G/2G para reducir al mínimo las zonas de sombra en entornos boscosos o de montaña. Es una herramienta ideal de adiestramiento por vibración o sonido, permitiéndote enseñar de forma positiva a tu mascota a volver a casa a la hora de comer. La batería integrada ofrece una autonomía de unos 3 días promedio, y cuenta con un ajuste perfecto en collares tradicionales."
  },
  {
    id: 3,
    name: "Weenect Dog Localizador GPS Impermeable con Alerta Antifuga",
    marca: "Weenect",
    category: "Mixto",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/71FPyG+WWUL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4wjPoP4",
    isFeatured: false,
    valoracion_media: 4.2,
    pros: "Localización en vivo sin límites de distancia|Alerta inmediata si sale de las zonas seguras|Linterna LED integrada para búsquedas en la oscuridad|Historial detallado de todas sus rutas",
    contras: "Exige plan de suscripción mensual|Curva de configuración inicial técnica",
    radar_scores: [8, 6, 8, 8, 8, 8],
    description: "Este robusto localizador Weenect Dog ofrece un seguimiento continuo y de excelente fiabilidad tanto en campo abierto como en áreas urbanas complejas. Cuenta con un receptor satelital de alta sensibilidad que proporciona la geolocalización de tu perro segundo a segundo, enviando alertas de escape instantáneas al móvil si el animal cruza los límites de seguridad virtuales configurados. Una de sus cualidades más destacables es la incorporación de una linterna LED de seguridad integrada para facilitar las búsquedas nocturnas y de un timbre sonoro para adiestrar al perro a regresar al escuchar el sonido. Cuenta con una estructura totalmente impermeable a prueba de inmersiones IP67, ideal para perros que corren libres en la naturaleza bajo cualquier clima."
  },
  {
    id: 4,
    name: "Tractive GPS Adventure Localizador Reforzado para Perros",
    marca: "Tractive",
    category: "Caza",
    tipo_uso: "caza",
    image_url: "https://m.media-amazon.com/images/I/81hjcH1tQGL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4gg0qjI",
    isFeatured: true,
    valoracion_media: 4.7,
    pros: "Carcasa ultra resistente ideal para senderismo y campo|Totalmente sumergible en agua dulce o salada|Alertas de valla virtual instantáneas en el móvil|Rastreo de actividad física y quema de calorías",
    contras: "Requiere cuota de suscripción periódica|Es ligeramente más pesado que el modelo estándar",
    radar_scores: [9, 7, 9, 7, 9, 8],
    description: "Diseñado para los perros más intrépidos y activos, el Tractive GPS Adventure cuenta con una carcasa protectora reforzada contra golpes severos, arañazos y mordidas accidentales. Es totalmente sumergible en agua dulce o salada gracias a su alto grado de protección hidrófuga, convirtiéndose en el compañero perfecto para la caza, el senderismo en montaña y los chapuzones fluviales. Incorpora una tarjeta SIM multi-red internacional para ofrecer localización precisa en tiempo real cada 3 segundos, alertas de valla virtual instantáneas en tu smartphone y un riguroso análisis de calorías y salud física de la mascota. Su batería optimizada de larga autonomía ofrece un rendimiento excelente de hasta 10 días."
  },
  {
    id: 5,
    name: "PAJ GPS Localizador para Perros 4G de Cobertura Global",
    marca: "PAJ GPS",
    category: "Mixto",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/810j0GUWuZL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4gbMjvL",
    isFeatured: false,
    valoracion_media: 4.4,
    pros: "Tecnología 4G de alta velocidad con excelente cobertura|Alertas de velocidad y salida de valla de seguridad|Materiales alemanes de gran durabilidad y tacto suave|Funda de silicona resistente a las salpicaduras",
    contras: "Requiere suscripción activa para usar la SIM|Dimensiones óptimas para perros de más de 4.5kg",
    radar_scores: [9, 8, 9, 8, 8, 8],
    description: "Con una potente antena receptora de gran sensibilidad y conectividad 4G LTE de última generación, este localizador alemán de la marca PAJ GPS te asegura encontrar a tu perro de forma rápida y milimétrica en cualquier rincón de Europa. Ofrece notificaciones en vivo si se traspasa el perímetro virtual de valla de seguridad establecido en la app, avisos por exceso de velocidad y un registro del historial de rutas de hasta 100 días para estudiar el comportamiento de tu mascota. Su construcción resistente incluye una funda de silicona muy agradable al tacto y protección contra salpicaduras de agua, resultando ideal para perros medianos y grandes activos."
  },
  {
    id: 6,
    name: "Localizador GPS Inteligente sin Cuotas compatible iOS",
    marca: "Compatible iOS",
    category: "Urbano",
    tipo_uso: "urbano",
    image_url: "https://m.media-amazon.com/images/I/81CJmBZhnQL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4bhtVhu",
    isFeatured: false,
    valoracion_media: 4.1,
    pros: "Completamente libre de suscripciones y cuotas mensuales|Batería reemplazable estándar de un año de duración|Integración perfecta con la aplicación Buscar de Apple|Ultra ligero y cómodo para gatos y perros pequeños",
    contras: "No es GPS satelital en tiempo real directo|Depende de la cercanía de dispositivos Apple",
    radar_scores: [6, 10, 5, 9, 7, 9],
    description: "Este ligero localizador es compatible con iOS y representa la alternativa ideal para entornos urbanos sin cuotas mensuales ni tarifas recurrentes. Se integra directamente con la red Buscar (Find My) de Apple, permitiendo localizar a tu mascota de forma segura mediante la señal triangulada de forma anónima por millones de dispositivos iPhone de la comunidad. Con un peso insignificante de apenas 12 gramos y un año entero de autonomía gracias a su pila reemplazable estándar, este dispositivo elimina por completo las recargas semanales. Aunque carece de chip GPS independiente y cobertura continua en áreas naturales despobladas, resulta una opción barata y funcional para mantener localizados a perros pequeños y gatos en la ciudad."
  },
  {
    id: 7,
    name: "Valla Inalámbrica Inteligente y GPS de Entrenamiento",
    marca: "Inalámbrico",
    category: "Caza",
    tipo_uso: "caza",
    image_url: "https://m.media-amazon.com/images/I/71KdcdE2cSL._AC_SL1500_.jpg",
    affiliate_link: "https://www.amazon.es/dp/B0F48FZLSS?tag=sosa0af-21",
    isFeatured: false,
    valoracion_media: 4.0,
    pros: "Valla de seguridad circular GPS totalmente portátil|Sin cuotas de suscripción de ningún tipo|Rango de control amplio ideal para parcelas grandes|Collar impermeable y resistente para exteriores",
    contras: "Diseñado para exteriores despejados, no interiores|No rastrea rutas paso a paso",
    radar_scores: [7, 8, 9, 6, 6, 8],
    description: "Este innovador collar combina un sistema de valla inalámbrica circular GPS inteligente con alertas acústicas y de vibración de adiestramiento. Te permite establecer límites virtuales fijos para que tu mascota permanezca en tu finca rústica o parcela sin necesidad de instalar pesados vallados físicos o cables subterráneos. Si el animal supera el perímetro radial, el collar emite señales disuasorias seguras para enseñarle a retornar al centro de la parcela. Al ser completamente portátil e impermeable, es el accesorio de adiestramiento idóneo para viajes, estancias en el campo o áreas de exterior despejadas, sin cuotas de suscripción asociadas."
  },
  {
    id: 8,
    name: "Rastreador GPS para Mascotas Impermeable con Salud",
    marca: "Rastreador",
    category: "Urbano",
    tipo_uso: "urbano",
    image_url: "https://m.media-amazon.com/images/I/81lKNe9TWaL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4f8IZ3r",
    isFeatured: false,
    valoracion_media: 4.2,
    pros: "Excelente precisión de posicionamiento satelital|Resistencia al agua certificada IP68 contra chapuzones|Seguimiento del ejercicio diario y calorías de la mascota|Notificaciones rápidas en pantalla de tu smartphone",
    contras: "Requiere suscripción activa para la red de datos|Autonomía típica de unos 5 días",
    radar_scores: [8, 7, 8, 8, 7, 8],
    description: "Un sofisticado localizador GPS integral para mascotas que combina de forma eficaz la precisión satelital de posicionamiento con un detallado monitor de salud y bienestar de tu perro o gato. Este dispositivo estanco IP68 monitoriza el nivel de actividad de tu mascota, la quema de calorías diarias y evalúa la calidad del sueño, lo que te permite detectar anomalías físicas o de fatiga antes de que sea tarde. A través de su aplicación, se configuran alarmas de escape instantáneas y vallas seguras en el mapa. Funciona con un plan de datos para garantizar el rastreo en tiempo real ilimitado, ofreciendo un equilibrio óptimo entre prevención médica y seguridad."
  },
  {
    id: 9,
    name: "Localizador GPS con Micrófono y Llamada sin Suscripción",
    marca: "Suscripción Libre",
    category: "Mixto",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/61JDzYQzN6L._AC_SL1000_.jpg",
    affiliate_link: "https://amzn.to/4aqJD9R",
    isFeatured: false,
    valoracion_media: 3.9,
    pros: "Totalmente libre de cuotas mensuales fijas de la marca|Micrófono integrado para escuchar el entorno de la mascota|Soporta llamadas de voz de retorno rápidas|Localización exacta mediante satélites GPS en vivo",
    contras: "Debes comprar tu propia tarjeta SIM de prepago|La aplicación móvil utiliza una interfaz genérica",
    radar_scores: [8, 8, 7, 7, 6, 9],
    description: "Un rastreador de seguridad que destaca por su micrófono integrado de alta sensibilidad y su capacidad para realizar llamadas de voz bidireccionales y de retorno rápido. Este dispositivo te permite escuchar con total nitidez lo que sucede alrededor de tu perro o gato cuando no lo tienes a la vista. Funciona mediante la inserción de una tarjeta SIM convencional de prepago que tú elijas de cualquier operador telefónico local, lo que te permite evitar por completo los planes de suscripción de la marca. Ofrece geolocalización satelital precisa, valla virtual y alertas directas al móvil, representando una excelente alternativa económica y versátil."
  },
  {
    id: 10,
    name: "Localizador GPS Compacto Universal sin Cuotas de Servicio",
    marca: "Inteligente",
    category: "Urbano",
    tipo_uso: "urbano",
    image_url: "https://m.media-amazon.com/images/I/61AJJ+gBTAL._AC_.jpg",
    affiliate_link: "https://amzn.to/4gaXLYv",
    isFeatured: false,
    valoracion_media: 3.8,
    pros: "Sin suscripción de por vida para el servicio de mapas|Diseño sumamente compacto adaptable a cualquier mascota|Funda de silicona de protección anticaídas incluida|Ubicación precisa en tiempo real en zonas cubiertas",
    contras: "La configuración inicial se realiza mediante comandos SMS|Manual de instrucciones poco detallado",
    radar_scores: [7, 7, 6, 9, 6, 8],
    description: "El localizador GPS compacto universal inteligente es un dispositivo sumamente versátil y económico, ideal para aquellos propietarios que buscan seguridad básica sin pagar cuotas de servicio mensuales. El rastreador funciona enviando la ubicación exacta en tiempo real en formato de coordenadas de Google Maps directamente a tu smartphone a través de alertas SMS rápidas o una tarjeta de red básica. Su configuración técnica inicial se realiza directamente mediante comandos SMS lógicos que vinculan el número de tu móvil con el collar. Su diseño de peso ligero se acopla a la perfección en arneses y collares tradicionales gracias a su funda elástica de silicona suave incluida para amortiguar golpes, caídas o la lluvia."
  },
  {
    id: 11,
    name: "Localizador GPS de Gatos y Mascotas sin Suscripción",
    marca: "Cat Tracker",
    category: "Mini",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/81vYd6WcyDL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4eQFcX3",
    isFeatured: false,
    valoracion_media: 3.7,
    pros: "Sin suscripciones fijas ni cuotas mensuales adicionales|Muy liviano e ideal para gatos y perros miniatura|Estuche de silicona flexible de ajuste perfecto|Localización precisa en campo abierto",
    contras: "Capacidad de batería reducida debido a su ligereza|Menor cobertura en interiores de edificios",
    radar_scores: [7, 6, 6, 10, 6, 8],
    description: "Este mini rastreador está especialmente optimizado para gatos exploradores y perros miniatura de peso muy reducido. Su diseño compacto y peso pluma de 25 gramos garantizan que tu mascota no sentirá ninguna molestia al trepar o correr libremente. Se entrega con una funda elástica de silicona flexible de ajuste milimétrico para collares estándar. Ofrece una localización satelital confiable en exteriores y es totalmente libre de suscripciones de la marca, funcionando mediante tarjeta SIM prepago para transmitir alertas geográficas. Es la mejor opción para descubrir las andanzas de tu gato sin cargos mensuales fijos."
  },
  {
    id: 12,
    name: "TKMARS Localizador GPS de Alta Autonomía y Resistencia",
    marca: "TKMARS",
    category: "Caza",
    tipo_uso: "caza",
    image_url: "https://m.media-amazon.com/images/I/61B-hjmY9dL._AC_SL1000_.jpg",
    affiliate_link: "https://amzn.to/3Qv7v5x",
    isFeatured: false,
    valoracion_media: 4.5,
    pros: "Batería descomunal de larga autonomía (hasta 30 días)|Precisión satelital insuperable en zonas boscosas|Estructura estanca de alta resistencia ante golpes|Historial completo de rutas de los últimos 180 días",
    contras: "Ligeramente voluminoso para mascotas de menos de 5 kg|No recomendado para felinos pequeños",
    radar_scores: [9, 10, 9, 6, 7, 8],
    description: "El TKMARS es el coloso de la autonomía en el mercado de collares GPS para perros de caza, senderismo avanzado o alta montaña. Equipado con una batería descomunal recargable, este robusto dispositivo ofrece hasta 30 días de duración en modo de ahorro inteligente, reduciendo drásticamente la molestia de las cargas continuas. Su antena GPS de grado profesional proporciona una precisión satelital insuperable incluso en zonas boscosas densas, barrancos o terrenos agrestes sin cobertura urbana. Su estructura robusta y estanca resiste arañazos, mordidas de otros animales y la suciedad del campo, almacenando además un historial técnico completo de rutas de los últimos 180 días."
  },
  {
    id: 13,
    name: "Pawfit 2 Localizador GPS Inteligente de Mascotas",
    marca: "Pawfit",
    category: "Mixto",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/6178B4jDKkL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/3Rerbuy",
    isFeatured: false,
    valoracion_media: 4.4,
    pros: "Monitoreo completo de salud y nivel de actividad|Comandos de voz personalizados que puedes reproducir de lejos|Protección impermeable premium IP68 a prueba de buceo|Alarma de temperatura extrema para tu tranquilidad",
    contras: "Plan de suscripción mensual obligatorio|Fijación al collar un poco rígida",
    radar_scores: [8, 7, 8, 8, 9, 8],
    description: "El collar inteligente Pawfit 2 destaca por combinar un rastreo de excelente precisión satelital con un avanzado monitor de bienestar y comandos de voz interactivos. Te permite grabar comandos de voz propios para que se reproduzcan directamente en el altavoz del collar de forma remota, facilitando el adiestramiento y el retorno positivo del perro a tu posición. Cuenta con sensores de bienestar físico, podómetro, un historial detallado de actividad física y una útil alarma de temperatura extrema para avisarte si el entorno de tu mascota es helado o excesivamente cálido. Su armadura estanca IP68 es sumamente dura y soporta inmersiones prolongadas y golpes directos, requiriendo una suscripción mensual estándar de la marca."
  },
  {
    id: 14,
    name: "PETLOC8 Localizador GPS con Luces de Seguridad",
    marca: "PETLOC8",
    category: "Urbano",
    tipo_uso: "urbano",
    image_url: "https://m.media-amazon.com/images/I/81OB0BI6LkL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/3Qv7wX9",
    isFeatured: false,
    valoracion_media: 4.1,
    pros: "Luz de seguridad LED integrada para paseos nocturnos|Excelente aplicación con interfaz intuitiva en español|Muy cómodo y fácil de abrochar en cualquier arnés|Notificaciones rápidas al salir del perímetro virtual",
    contras: "Suscripción obligatoria para activar la tarjeta SIM|La cobertura se puede ver mermada en valles profundos",
    radar_scores: [8, 6, 8, 9, 8, 7],
    description: "El PETLOC8 es un sofisticado collar GPS para perros especialmente diseñado para garantizar la máxima visibilidad en paseos nocturnos o en condiciones de baja luminosidad gracias a su potente luz de seguridad LED integrada, la cual puedes activar de forma remota a través de su cómoda aplicación móvil en español. El localizador ofrece una localización continua en vivo en el mapa, alertas instantáneas cuando tu perro cruza los límites de la valla virtual establecida, y estadísticas del ejercicio diario. Cuenta con una hebilla ajustable muy suave para colocarlo con facilidad en collares o arneses de forma cómoda, requiriendo un plan de suscripción celular para su conectividad multi-red."
  },
  {
    id: 15,
    name: "Localizador GPS sin Suscripción Universal Perros y Gatos",
    marca: "Suscripción Libre",
    category: "Mixto",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/71LHcK-1mgL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4vb2TzN",
    isFeatured: false,
    valoracion_media: 4.0,
    pros: "Totalmente libre de tarifas y cuotas mensuales fijas|Diseño versátil apto tanto para perros como para gatos|Configuración rápida de valla virtual mediante app|Batería duradera con modo de ahorro inteligente",
    contras: "Se requiere adquirir una tarjeta SIM móvil prepago|No registra mapas de calor de comportamiento",
    radar_scores: [8, 8, 7, 9, 6, 9],
    description: "Una de las mejores alternativas de gran rentabilidad para geolocalizar a tu mascota en tiempo real sin contratos fijos ni suscripciones obligatorias. Este rastreador GPS universal funciona introduciendo una tarjeta SIM prepago estándar de tu elección para transmitir las alertas de valla virtual y las coordenadas de posición de tu perro o gato directamente a tu smartphone de forma económica. Cuenta con una carcasa hermética de gran resistencia a la lluvia y al polvo, y un sistema inteligente de ahorro de batería que reduce el consumo cuando el animal está en reposo, garantizándote un control seguro y duradero."
  },
  {
    id: 16,
    name: "Winnes Localizador GPS con Estadísticas de Bienestar",
    marca: "Winnes",
    category: "Urbano",
    tipo_uso: "urbano",
    image_url: "https://m.media-amazon.com/images/I/61o9+MxmjGL._AC_SL1200_.jpg",
    affiliate_link: "https://amzn.to/4wd3lOG",
    isFeatured: false,
    valoracion_media: 4.1,
    pros: "Análisis pormenorizado de actividad y descanso|Diseño premium con funda elástica de silicona suave|Rastreo continuo en vivo muy fluido en el mapa|Excelente empaquetado e instrucciones claras",
    contras: "Suscripción móvil obligatoria para la tarjeta celular|Tiempo de recarga de batería de unas 3 horas",
    radar_scores: [8, 6, 8, 8, 8, 8],
    description: "El rastreador de la marca Winnes destaca por su refinada aplicación que proporciona estadísticas del bienestar físico y el descanso diario de tu perro. Ofrece un seguimiento satelital continuo en tiempo real de alta fluidez en el mapa, eliminando molestos saltos o pérdidas de señal bruscas durante el paseo. Viene acompañado de una funda elástica de silicona suave que se adapta con facilidad al collar habitual de tu mascota sin añadir un peso excesivo, resultando ideal para cuidar la salud física, el peso óptimo y evitar las pérdidas accidentales en entornos urbanos y de parques mediante valla virtual."
  },
  {
    id: 17,
    name: "Tractive CAT Mini Localizador GPS para Gatos con Collar",
    marca: "Tractive",
    category: "Mini",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/71hJIvr80oL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4bdLvD1",
    isFeatured: true,
    valoracion_media: 4.5,
    pros: "Diseño ergonómico exclusivo para la anatomía del gato|Collar de seguridad Rogz con cierre anti-enganches|Mapa de calor de territorio para ver dónde pasa el tiempo|Rastreo en vivo sin límites de distancia",
    contras: "Requiere plan de suscripción mensual|Autonomía máxima de 2 a 3 días",
    radar_scores: [9, 5, 8, 10, 9, 8],
    description: "El Tractive CAT Mini es el primer rastreador GPS optimizado exclusivamente para la anatomía ligera y hábitos nocturnos de los felinos domésticos. Viene equipado de serie con un collar de seguridad Rogz de alta calidad que dispone de un sistema de liberación de seguridad ajustable, diseñado para abrirse de forma automática ante tirones si el gato se engancha en una valla o rama de árbol. Cuenta con la función exclusiva de mapa de calor de territorio para descubrir las andanzas de tu gato en el vecindario, vallas de alarma instantánea de escape y un análisis pormenorizado de la salud y calidad del sueño de tu mascota, requiriendo un plan de suscripción de Tractive."
  },
  {
    id: 18,
    name: "Kippy Cat V2 Localizador de Gatos Antiestrangulamiento",
    marca: "Kippy",
    category: "Mini",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/71I5w9Fks1L._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4vHUF37",
    isFeatured: false,
    valoracion_media: 4.2,
    pros: "Collar especial de seguridad antiestrangulamiento incluido|Seguimiento detallado de la actividad física y sueño|Ubicación precisa en tiempo real con actualizaciones rápidas|Alertas instantáneas de salida de zonas seguras",
    contras: "Suscripción activa obligatoria|Batería de unos 2 días en seguimiento continuo",
    radar_scores: [8, 5, 8, 9, 8, 7],
    description: "El Kippy Cat V2 es una opción premium de alto confort que viene equipada con un collar elástico de seguridad antiestrangulamiento incorporado para evitar asfixias accidentales en gatos salvajes o muy activos en el exterior. Su chip de posicionamiento en vivo proporciona coordenadas de ubicación ultra rápidas actualizadas cada 4 segundos, alertas de escape instantáneas y vallas de seguridad. Su aplicación monitoriza al detalle las actividades de rascado, descanso profundo, juego y carreras del felino, brindando recomendaciones veterinarias personalizadas para mejorar su bienestar y longevidad."
  },
  {
    id: 19,
    name: "Denash Localizador GPS de Acople para Collar de Mascotas",
    marca: "Denash",
    category: "Mixto",
    tipo_uso: "mixto",
    image_url: "https://m.media-amazon.com/images/I/61dkHLJTpVL._AC_SL1500_.jpg",
    affiliate_link: "https://amzn.to/4vHNojO",
    isFeatured: false,
    valoracion_media: 3.9,
    pros: "Ligero y compacto de fácil sujeción a collares estándar|Sin suscripciones fijas ni cuotas mensuales recurrentes|Localización SMS rápida y consumo de datos bajísimo|Buena resistencia al polvo y salpicaduras",
    contras: "Requiere que proporciones tu propia tarjeta SIM activa|No cuenta con sensores de salud",
    radar_scores: [7, 8, 6, 9, 6, 8],
    description: "El localizador GPS de acople universal Denash es un dispositivo independiente de gran funcionalidad que se fija a presión directamente a cualquier correa de cuero, nailon o silicona que tu perro o gato ya posea. Es un rastreador totalmente libre de suscripción obligatoria, por lo que funciona introduciendo tu propia tarjeta SIM activa y enviando alertas SMS de ubicación rápidas que se enlazan directamente a mapas interactivos en Google Maps en tu móvil. Su bajo consumo de batería y datos móviles, sumado a su gran resistencia a la lluvia y el barro, lo convierten en una opción sumamente económica y confiable."
  }
];
